function [] = Main()

    clear all;
    clc;
    
    %% Random
    rng(1)

    Constants = struct();
    Setup % Setup file with constant value
    
    %% Setup stuff
       
    % Setup stuff
    load_file_setup = sprintf('Setup_Mats_BTO_pct%g_%gx%gy%gz_%g_%g.mat',...
        Constants.BTO_pct,Constants.Nx,Constants.Ny,Constants.Nz,Constants.interface_index,Constants.film_index);
    
    if( exist(load_file_setup) )
        load(load_file_setup);
    else
        % Setup energy stuff
        if(VPA_ELASTIC_ON)
%            InfinitePlateSetup_vpa(Constants, kx_grid_2D, ky_grid_2D);
            return
        else
            [strain_bc_mats_inv, strain_bc_mat_inv_korigin, ...
            strain_sol_2Dk_1, strain_sol_2Dk_2, strain_sol_2Dk_3, ...
            strain_sol_2Dk_4, strain_sol_2Dk_5, strain_sol_2Dk_6, ...
            strain_sol_2Dk_d3_1, strain_sol_2Dk_d3_2, strain_sol_2Dk_d3_3, ...
            strain_sol_2Dk_d3_4, strain_sol_2Dk_d3_5, strain_sol_2Dk_d3_6, ...
            strain_bc_mats_L_inv_lu, strain_bc_mats_U_lu, strain_bc_mats_P_lu] = InfinitePlateSetup(Constants, kx_grid_2D, ky_grid_2D);
        end

        if(VPA_ELECTRIC_ON)
%            ElectrostaticSetup_vpa(Constants, kx_grid_2D, ky_grid_2D);
             return
        else
            [electric_bc_mats_inv, electric_bc_mats_inv_korigin, ...
            potential_2Dk_sol_1, potential_2Dk_sol_2, ...
            potential_2Dk_d3_sol_1, potential_2Dk_d3_sol_2] = ElectrostaticSetup(Constants, kx_grid_2D, ky_grid_2D);       
        end

        [...
        Green_11, Green_12, Green_13, ...
        Green_21, Green_22, Green_23, ...
        Green_31, Green_32, Green_33] = GreenTensorSetup(Constants, ...
                                        kx_grid_3D, ky_grid_3D, kz_grid_3D);
                                    
        [q_mat_1_1stOrd, q_mat_2_1stOrd, q_mat_3_1stOrd, ...
        scaling_1_1stOrd, scaling_2_1stOrd, scaling_3_1stOrd, ...
        TimeCoeffs_inv_mat_1_1stOrd, TimeCoeffs_inv_mat_2_1stOrd, TimeCoeffs_inv_mat_3_1stOrd] = ...
                        TimeStepSetup_1stOrd(Constants, kx_grid_2D, ky_grid_2D, z_axis);
                    
        [q_mat_1_2ndOrd, q_mat_2_2ndOrd, q_mat_3_2ndOrd, ...
        scaling_1_2ndOrd, scaling_2_2ndOrd, scaling_3_2ndOrd, ...
        TimeCoeffs_inv_mat_1_2ndOrd, TimeCoeffs_inv_mat_2_2ndOrd, TimeCoeffs_inv_mat_3_2ndOrd] = ...
                        TimeStepSetup_2ndOrd(Constants, kx_grid_2D, ky_grid_2D, z_axis);

%         save(load_file_setup,...
%         'strain_bc_mats_inv','strain_bc_mat_inv_korigin',...
%         'eigenvec_mat','eigenval_mat',...
%         'electric_bc_mats_inv','electric_bc_mats_inv_korigin',...
%         'Green_11','Green_12','Green_13',...
%         'Green_21','Green_22','Green_23',...
%         'Green_31','Green_32','Green_33',...
%         'TimeCoeffs_inv_mat_1_1stOrd', 'TimeCoeffs_inv_mat_2_1stOrd', 'TimeCoeffs_inv_mat_3_1stOrd',...
%         'q_mat_1_1stOrd', 'q_mat_2_1stOrd', 'q_mat_3_1stOrd',...
%         'scaling_1_1stOrd', 'scaling_2_1stOrd', 'scaling_3_1stOrd',...
%         'TimeCoeffs_inv_mat_1_2ndOrd', 'TimeCoeffs_inv_mat_2_2ndOrd', 'TimeCoeffs_inv_mat_3_2ndOrd',...
%         'q_mat_1_2ndOrd', 'q_mat_2_2ndOrd', 'q_mat_3_2ndOrd',...
%         'scaling_1_2ndOrd', 'scaling_2_2ndOrd', 'scaling_3_2ndOrd');
    end
    
    %% Initial conditions
    [P1_0, P2_0, P3_0] = InitP(in_film, LOAD, Constants.Nx, Constants.Ny, Constants.Nz);
    [f1_0, f2_0, f3_0, u_1, u_2, u_3, Potential, ...
    TotalStrain_11, TotalStrain_12, TotalStrain_13, ...
    TotalStrain_22, TotalStrain_23, TotalStrain_33, ...
    E_1_depol, E_2_depol, E_3_depol] = ...
                    CalcEnergies(P1_0, P2_0, P3_0, Constants, ...
                            Green_11, Green_12, Green_13, ...
                            Green_21, Green_22, Green_23, ...
                            Green_31, Green_32, Green_33, ...
                            strain_bc_mats_inv, strain_bc_mat_inv_korigin, ...
                            electric_bc_mats_inv, electric_bc_mats_inv_korigin, ...
                            kx_grid_3D, ky_grid_3D, kz_grid_3D, z_axis, ...
                            strain_sol_2Dk_1, strain_sol_2Dk_2, strain_sol_2Dk_3, ...
                            strain_sol_2Dk_4, strain_sol_2Dk_5, strain_sol_2Dk_6, ...
                            strain_sol_2Dk_d3_1, strain_sol_2Dk_d3_2, strain_sol_2Dk_d3_3, ...
                            strain_sol_2Dk_d3_4, strain_sol_2Dk_d3_5, strain_sol_2Dk_d3_6, ...
                            potential_2Dk_sol_1, potential_2Dk_sol_2, ...
                            potential_2Dk_d3_sol_1, potential_2Dk_d3_sol_2, ...
                            strain_bc_mats_L_inv_lu, strain_bc_mats_U_lu, strain_bc_mats_P_lu);

    % First iteration
    [P1_1, P2_1, P3_1] = TimeStep_1stOrd(P1_0, P2_0, P3_0, f1_0, f2_0, f3_0, ...
                            TimeCoeffs_inv_mat_1_1stOrd, TimeCoeffs_inv_mat_2_1stOrd, TimeCoeffs_inv_mat_3_1stOrd, ...
                            q_mat_1_1stOrd, q_mat_2_1stOrd, q_mat_3_1stOrd, ...
                            scaling_1_1stOrd, scaling_2_1stOrd, scaling_3_1stOrd, ...
                            Constants, kx_grid_3D, ky_grid_3D, kz_grid_3D, z_axis);   
 
    [f1_1, f2_1, f3_1, u_1, u_2, u_3, Potential, ...
    TotalStrain_11, TotalStrain_12, TotalStrain_13, ...
    TotalStrain_22, TotalStrain_23, TotalStrain_33, ...
    E_1_depol, E_2_depol, E_3_depol] = ...
                        CalcEnergies(P1_1, P2_1, P3_1, Constants, ...
                        Green_11, Green_12, Green_13, ...
                        Green_21, Green_22, Green_23, ...
                        Green_31, Green_32, Green_33, ...
                        strain_bc_mats_inv, strain_bc_mat_inv_korigin, ...
                        electric_bc_mats_inv, electric_bc_mats_inv_korigin, ...
                        kx_grid_3D, ky_grid_3D, kz_grid_3D, z_axis, ...
                        strain_sol_2Dk_1, strain_sol_2Dk_2, strain_sol_2Dk_3, ...
                        strain_sol_2Dk_4, strain_sol_2Dk_5, strain_sol_2Dk_6, ...
                        strain_sol_2Dk_d3_1, strain_sol_2Dk_d3_2, strain_sol_2Dk_d3_3, ...
                        strain_sol_2Dk_d3_4, strain_sol_2Dk_d3_5, strain_sol_2Dk_d3_6, ...
                        potential_2Dk_sol_1, potential_2Dk_sol_2, ...
                        potential_2Dk_d3_sol_1, potential_2Dk_d3_sol_2, ...
                        strain_bc_mats_L_inv_lu, strain_bc_mats_U_lu, strain_bc_mats_P_lu);
    c = 1; % Flag for do while loop
    error = inf;
    
    saves = Constants.saves;
    errors = zeros(saves(end),1);
    
    if( 7 ~= exist(PATH,'dir'))
        mkdir(PATH);
    end
    
    %% Main loop
    P1 = P1_0; P2 = P2_0; P3 = P3_0;
    save(sprintf('%s%g.mat',PATH,0),'P1','P2','P3');
    while (c == 1 || error > epsilon) && c < saves(end)

        % saving 
        if( sum(c == saves) == 1 )        
            save(sprintf('%s%g.mat',PATH,c),'P1','P2','P3');
        end        

        % Time Step energy and P to (t + 2 * dt) P: (P1, P2, P3)
        [P1, P2, P3] = TimeStep_2ndOrd(P1_0, P2_0, P3_0, ...
                            P1_1, P2_1, P3_1, ...
                            f1_0, f2_0, f3_0, ...
                            f1_1, f2_1, f3_1, ...
                            TimeCoeffs_inv_mat_1_2ndOrd, TimeCoeffs_inv_mat_2_2ndOrd, TimeCoeffs_inv_mat_3_2ndOrd, ...
                            q_mat_1_2ndOrd, q_mat_2_2ndOrd, q_mat_3_2ndOrd, ...
                            scaling_1_2ndOrd, scaling_2_2ndOrd, scaling_3_2ndOrd, ...
                            Constants, kx_grid_3D, ky_grid_3D, kz_grid_3D, z_axis);
                               
        % Energies for this time step (t + 2*dt) energies (f1, f2, f3)
        [f1, f2, f3, u_1, u_2, u_3, Potential, ...
        TotalStrain_11, TotalStrain_12, TotalStrain_13, ...
        TotalStrain_22, TotalStrain_23, TotalStrain_33, ...
        E_1_depol, E_2_depol, E_3_depol] = ...
                        CalcEnergies(P1, P2, P3, Constants, ...
                            Green_11, Green_12, Green_13, ...
                            Green_21, Green_22, Green_23, ...
                            Green_31, Green_32, Green_33, ...
                            strain_bc_mats_inv, strain_bc_mat_inv_korigin, ...
                            electric_bc_mats_inv, electric_bc_mats_inv_korigin, ...
                            kx_grid_3D, ky_grid_3D, kz_grid_3D, z_axis, ...
                            strain_sol_2Dk_1, strain_sol_2Dk_2, strain_sol_2Dk_3, ...
                            strain_sol_2Dk_4, strain_sol_2Dk_5, strain_sol_2Dk_6, ...
                            strain_sol_2Dk_d3_1, strain_sol_2Dk_d3_2, strain_sol_2Dk_d3_3, ...
                            strain_sol_2Dk_d3_4, strain_sol_2Dk_d3_5, strain_sol_2Dk_d3_6, ...
                            potential_2Dk_sol_1, potential_2Dk_sol_2, ...
                            potential_2Dk_d3_sol_1, potential_2Dk_d3_sol_2, ...
                            strain_bc_mats_L_inv_lu, strain_bc_mats_U_lu, strain_bc_mats_P_lu);
                        
        % Setup for next loops
        % t takes on t + dt values
        P1_0 = P1_1; P2_0 = P2_1; P3_0 = P3_1;
        f1_0 = f1_1; f2_0 = f2_1; f3_0 = f3_1;
        
        % t + dt takes on t + 2 * dt values
        P1_1 = P1; P2_1 = P2; P3_1 = P3;
        f1_1 = f1; f2_1 = f2; f3_1 = f3;
                        
        % Progress
        error = max( [sum(sum(sum(abs(P1_1-P1_0)))); sum(sum(sum(abs(P2_1-P2_0)))); sum(sum(sum(abs(P3_1-P3_0))))] );
        errors(c) = error;
        % print error
        if( mod(c, 50) == 0 )
            Visualize
            drawnow
            error   
        end
        
        c = c + 1;

    end

    HomoStrain_11 = TotalStrain_homo_11(P1,P2,P3,Constants); 
    HomoStrain_22 = TotalStrain_homo_22(P1,P2,P3,Constants); 
    HomoStrain_33 = TotalStrain_homo_33(P1,P2,P3,Constants); 
    HomoStrain_13 = TotalStrain_homo_13(P1,P2,P3,Constants); 
    HomoStrain_23 = TotalStrain_homo_23(P1,P2,P3,Constants); 
    HomoStrain_12 = TotalStrain_homo_12(P1,P2,P3,Constants);     

    save(sprintf('%sfinal__%g Us11__%g Us22__%gC__%gkV-cm__%s.mat',PATH,Us_11*1e2,Us_22*1e2,Temperature,E_1_applied/1e5,STRING),...
    'P1','P2','P3',...
    'u_1','u_2','u_3',...
    'TotalStrain_11', 'TotalStrain_12', 'TotalStrain_13', ...
    'TotalStrain_22', 'TotalStrain_23', 'TotalStrain_33', ...
    'HomoStrain_11', 'HomoStrain_22', 'HomoStrain_33', ...
    'HomoStrain_13', 'HomoStrain_23', 'HomoStrain_12', ...
    'Potential',...
    'E_1_depol', 'E_2_depol', 'E_3_depol', ...
    'x_axis','y_axis','z_axis',...
    'x_grid','y_grid','z_grid',...
    'Nx','Ny','Nz',...
    'VPA_ELECTRIC_ON','VPA_ELASTIC_ON','LOAD',...
    'Temperature','Us_11','Us_22','Us_12',...
    'errors','in_film'...
    );

    save(sprintf('%sfinal__%g Us11__%g Us22__%gC__%gkV-cm__%s_Constants.mat',PATH,Us_11*1e2,Us_22*1e2,Temperature,E_1_applied/1e5,STRING),...
    '-struct', 'Constants' ...
    );
   

end